// Elenco nazionalità (demonimi) in italiano e inglese, ISO 3166-1 alpha-2
export type Nationality = { code: string; it: string; en: string };

export const NATIONALITIES: Nationality[] = [
  { code: "AF", it: "Afghana", en: "Afghan" },
  { code: "AL", it: "Albanese", en: "Albanian" },
  { code: "DZ", it: "Algerina", en: "Algerian" },
  { code: "AD", it: "Andorrana", en: "Andorran" },
  { code: "AO", it: "Angolana", en: "Angolan" },
  { code: "AG", it: "Antiguo-barbudana", en: "Antiguan" },
  { code: "AR", it: "Argentina", en: "Argentine" },
  { code: "AM", it: "Armena", en: "Armenian" },
  { code: "AU", it: "Australiana", en: "Australian" },
  { code: "AT", it: "Austriaca", en: "Austrian" },
  { code: "AZ", it: "Azerbaigiana", en: "Azerbaijani" },
  { code: "BS", it: "Bahamense", en: "Bahamian" },
  { code: "BH", it: "Bahreinita", en: "Bahraini" },
  { code: "BD", it: "Bangladese", en: "Bangladeshi" },
  { code: "BB", it: "Barbadiana", en: "Barbadian" },
  { code: "BY", it: "Bielorussa", en: "Belarusian" },
  { code: "BE", it: "Belga", en: "Belgian" },
  { code: "BZ", it: "Beliziana", en: "Belizean" },
  { code: "BJ", it: "Beninese", en: "Beninese" },
  { code: "BT", it: "Bhutanese", en: "Bhutanese" },
  { code: "BO", it: "Boliviana", en: "Bolivian" },
  { code: "BA", it: "Bosniaca", en: "Bosnian" },
  { code: "BW", it: "Botswana", en: "Botswanan" },
  { code: "BR", it: "Brasiliana", en: "Brazilian" },
  { code: "BN", it: "Bruneiana", en: "Bruneian" },
  { code: "BG", it: "Bulgara", en: "Bulgarian" },
  { code: "BF", it: "Burkinabè", en: "Burkinabé" },
  { code: "BI", it: "Burundese", en: "Burundian" },
  { code: "KH", it: "Cambogiana", en: "Cambodian" },
  { code: "CM", it: "Camerunese", en: "Cameroonian" },
  { code: "CA", it: "Canadese", en: "Canadian" },
  { code: "CV", it: "Capoverdiana", en: "Cape Verdean" },
  { code: "CF", it: "Centrafricana", en: "Central African" },
  { code: "TD", it: "Ciadiana", en: "Chadian" },
  { code: "CL", it: "Cilena", en: "Chilean" },
  { code: "CN", it: "Cinese", en: "Chinese" },
  { code: "CY", it: "Cipriota", en: "Cypriot" },
  { code: "CO", it: "Colombiana", en: "Colombian" },
  { code: "KM", it: "Comoriana", en: "Comoran" },
  { code: "CG", it: "Congolese", en: "Congolese" },
  { code: "CD", it: "Congolese (RDC)", en: "Congolese (DRC)" },
  { code: "KP", it: "Nordcoreana", en: "North Korean" },
  { code: "KR", it: "Sudcoreana", en: "South Korean" },
  { code: "CI", it: "Ivoriana", en: "Ivorian" },
  { code: "CR", it: "Costaricana", en: "Costa Rican" },
  { code: "HR", it: "Croata", en: "Croatian" },
  { code: "CU", it: "Cubana", en: "Cuban" },
  { code: "DK", it: "Danese", en: "Danish" },
  { code: "DM", it: "Dominicana", en: "Dominican" },
  { code: "DO", it: "Dominicana (Rep.)", en: "Dominican (Rep.)" },
  { code: "EC", it: "Ecuadoriana", en: "Ecuadorian" },
  { code: "EG", it: "Egiziana", en: "Egyptian" },
  { code: "SV", it: "Salvadoregna", en: "Salvadoran" },
  { code: "AE", it: "Emiratina", en: "Emirati" },
  { code: "ER", it: "Eritrea", en: "Eritrean" },
  { code: "EE", it: "Estone", en: "Estonian" },
  { code: "ET", it: "Etiope", en: "Ethiopian" },
  { code: "FJ", it: "Figiana", en: "Fijian" },
  { code: "PH", it: "Filippina", en: "Filipino" },
  { code: "FI", it: "Finlandese", en: "Finnish" },
  { code: "FR", it: "Francese", en: "French" },
  { code: "GA", it: "Gabonese", en: "Gabonese" },
  { code: "GM", it: "Gambiana", en: "Gambian" },
  { code: "GE", it: "Georgiana", en: "Georgian" },
  { code: "DE", it: "Tedesca", en: "German" },
  { code: "GH", it: "Ghanese", en: "Ghanaian" },
  { code: "JM", it: "Giamaicana", en: "Jamaican" },
  { code: "JP", it: "Giapponese", en: "Japanese" },
  { code: "GI", it: "Gibilterriana", en: "Gibraltarian" },
  { code: "DJ", it: "Gibutiana", en: "Djiboutian" },
  { code: "JO", it: "Giordana", en: "Jordanian" },
  { code: "GR", it: "Greca", en: "Greek" },
  { code: "GD", it: "Grenadina", en: "Grenadian" },
  { code: "GT", it: "Guatemalteca", en: "Guatemalan" },
  { code: "GN", it: "Guineana", en: "Guinean" },
  { code: "GW", it: "Guineense (Bissau)", en: "Bissau-Guinean" },
  { code: "GQ", it: "Equatoguineana", en: "Equatorial Guinean" },
  { code: "GY", it: "Guyanese", en: "Guyanese" },
  { code: "HT", it: "Haitiana", en: "Haitian" },
  { code: "HN", it: "Honduregna", en: "Honduran" },
  { code: "IN", it: "Indiana", en: "Indian" },
  { code: "ID", it: "Indonesiana", en: "Indonesian" },
  { code: "IR", it: "Iraniana", en: "Iranian" },
  { code: "IQ", it: "Irachena", en: "Iraqi" },
  { code: "IE", it: "Irlandese", en: "Irish" },
  { code: "IS", it: "Islandese", en: "Icelandic" },
  { code: "IL", it: "Israeliana", en: "Israeli" },
  { code: "IT", it: "Italiana", en: "Italian" },
  { code: "KZ", it: "Kazaka", en: "Kazakh" },
  { code: "KE", it: "Keniota", en: "Kenyan" },
  { code: "KG", it: "Kirghisa", en: "Kyrgyz" },
  { code: "KI", it: "Kiribatiana", en: "Kiribati" },
  { code: "XK", it: "Kosovara", en: "Kosovar" },
  { code: "KW", it: "Kuwaitiana", en: "Kuwaiti" },
  { code: "LA", it: "Laotiana", en: "Laotian" },
  { code: "LS", it: "Lesothiana", en: "Basotho" },
  { code: "LV", it: "Lettone", en: "Latvian" },
  { code: "LB", it: "Libanese", en: "Lebanese" },
  { code: "LR", it: "Liberiana", en: "Liberian" },
  { code: "LY", it: "Libica", en: "Libyan" },
  { code: "LI", it: "Liechtensteinese", en: "Liechtensteiner" },
  { code: "LT", it: "Lituana", en: "Lithuanian" },
  { code: "LU", it: "Lussemburghese", en: "Luxembourgish" },
  { code: "MK", it: "Macedone", en: "Macedonian" },
  { code: "MG", it: "Malgascia", en: "Malagasy" },
  { code: "MW", it: "Malawiana", en: "Malawian" },
  { code: "MY", it: "Malese", en: "Malaysian" },
  { code: "MV", it: "Maldiviana", en: "Maldivian" },
  { code: "ML", it: "Maliana", en: "Malian" },
  { code: "MT", it: "Maltese", en: "Maltese" },
  { code: "MA", it: "Marocchina", en: "Moroccan" },
  { code: "MH", it: "Marshallese", en: "Marshallese" },
  { code: "MR", it: "Mauritana", en: "Mauritanian" },
  { code: "MU", it: "Mauriziana", en: "Mauritian" },
  { code: "MX", it: "Messicana", en: "Mexican" },
  { code: "FM", it: "Micronesiana", en: "Micronesian" },
  { code: "MD", it: "Moldava", en: "Moldovan" },
  { code: "MC", it: "Monegasca", en: "Monégasque" },
  { code: "MN", it: "Mongola", en: "Mongolian" },
  { code: "ME", it: "Montenegrina", en: "Montenegrin" },
  { code: "MZ", it: "Mozambicana", en: "Mozambican" },
  { code: "MM", it: "Birmana", en: "Burmese" },
  { code: "NA", it: "Namibiana", en: "Namibian" },
  { code: "NR", it: "Nauruana", en: "Nauruan" },
  { code: "NP", it: "Nepalese", en: "Nepali" },
  { code: "NI", it: "Nicaraguense", en: "Nicaraguan" },
  { code: "NE", it: "Nigerina", en: "Nigerien" },
  { code: "NG", it: "Nigeriana", en: "Nigerian" },
  { code: "NO", it: "Norvegese", en: "Norwegian" },
  { code: "NZ", it: "Neozelandese", en: "New Zealander" },
  { code: "OM", it: "Omanita", en: "Omani" },
  { code: "NL", it: "Olandese", en: "Dutch" },
  { code: "PK", it: "Pakistana", en: "Pakistani" },
  { code: "PW", it: "Palauana", en: "Palauan" },
  { code: "PS", it: "Palestinese", en: "Palestinian" },
  { code: "PA", it: "Panamense", en: "Panamanian" },
  { code: "PG", it: "Papuana", en: "Papua New Guinean" },
  { code: "PY", it: "Paraguaiana", en: "Paraguayan" },
  { code: "PE", it: "Peruviana", en: "Peruvian" },
  { code: "PL", it: "Polacca", en: "Polish" },
  { code: "PT", it: "Portoghese", en: "Portuguese" },
  { code: "QA", it: "Qatariota", en: "Qatari" },
  { code: "GB", it: "Britannica", en: "British" },
  { code: "CZ", it: "Ceca", en: "Czech" },
  { code: "RO", it: "Rumena", en: "Romanian" },
  { code: "RW", it: "Ruandese", en: "Rwandan" },
  { code: "RU", it: "Russa", en: "Russian" },
  { code: "KN", it: "Nevisiana", en: "Kittitian" },
  { code: "LC", it: "Santaluciana", en: "Saint Lucian" },
  { code: "VC", it: "Sanvincentina", en: "Saint Vincentian" },
  { code: "SB", it: "Salomonese", en: "Solomon Islander" },
  { code: "WS", it: "Samoana", en: "Samoan" },
  { code: "SM", it: "Sammarinese", en: "Sammarinese" },
  { code: "ST", it: "Saotomense", en: "São Toméan" },
  { code: "SA", it: "Saudita", en: "Saudi" },
  { code: "SN", it: "Senegalese", en: "Senegalese" },
  { code: "RS", it: "Serba", en: "Serbian" },
  { code: "SC", it: "Seychellese", en: "Seychellois" },
  { code: "SL", it: "Sierraleonese", en: "Sierra Leonean" },
  { code: "SG", it: "Singaporiana", en: "Singaporean" },
  { code: "SY", it: "Siriana", en: "Syrian" },
  { code: "SK", it: "Slovacca", en: "Slovak" },
  { code: "SI", it: "Slovena", en: "Slovenian" },
  { code: "SO", it: "Somala", en: "Somali" },
  { code: "ES", it: "Spagnola", en: "Spanish" },
  { code: "LK", it: "Singalese", en: "Sri Lankan" },
  { code: "US", it: "Statunitense", en: "American" },
  { code: "ZA", it: "Sudafricana", en: "South African" },
  { code: "SD", it: "Sudanese", en: "Sudanese" },
  { code: "SS", it: "Sudsudanese", en: "South Sudanese" },
  { code: "SR", it: "Surinamese", en: "Surinamese" },
  { code: "SE", it: "Svedese", en: "Swedish" },
  { code: "CH", it: "Svizzera", en: "Swiss" },
  { code: "SZ", it: "Swazi", en: "Swazi" },
  { code: "TJ", it: "Tagika", en: "Tajik" },
  { code: "TW", it: "Taiwanese", en: "Taiwanese" },
  { code: "TZ", it: "Tanzaniana", en: "Tanzanian" },
  { code: "TH", it: "Thailandese", en: "Thai" },
  { code: "TL", it: "Timorese", en: "Timorese" },
  { code: "TG", it: "Togolese", en: "Togolese" },
  { code: "TO", it: "Tongana", en: "Tongan" },
  { code: "TT", it: "Trinidadiana", en: "Trinidadian" },
  { code: "TN", it: "Tunisina", en: "Tunisian" },
  { code: "TR", it: "Turca", en: "Turkish" },
  { code: "TM", it: "Turkmena", en: "Turkmen" },
  { code: "TV", it: "Tuvaluana", en: "Tuvaluan" },
  { code: "UA", it: "Ucraina", en: "Ukrainian" },
  { code: "UG", it: "Ugandese", en: "Ugandan" },
  { code: "HU", it: "Ungherese", en: "Hungarian" },
  { code: "UY", it: "Uruguaiana", en: "Uruguayan" },
  { code: "UZ", it: "Uzbeka", en: "Uzbek" },
  { code: "VU", it: "Vanuatuana", en: "Ni-Vanuatu" },
  { code: "VA", it: "Vaticana", en: "Vatican" },
  { code: "VE", it: "Venezuelana", en: "Venezuelan" },
  { code: "VN", it: "Vietnamita", en: "Vietnamese" },
  { code: "YE", it: "Yemenita", en: "Yemeni" },
  { code: "ZM", it: "Zambiana", en: "Zambian" },
  { code: "ZW", it: "Zimbabwese", en: "Zimbabwean" },
];